# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19leqxVKzzNC50kW0DKqYvkyI9LvEs87e

## Gas Monitoring — EDA & Data Cleaning

## 1. Imports and Load Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_sql(
    "SELECT * FROM gas_monitoring",
    "sqlite:///gas_monitoring.db"
)

print(df.head())

"""## 2. Data Exploration

### Shape and types
"""

df.info()

"""10,000 rows, 14 columns. Most sensor columns are float64 meaning they are quantitative data. The 4 categorical columns are object.
Session ID is an integer.

### Summary statistics
"""

df.describe()

"""Temperature max of 307°C and Humidity max of 198 % and Humidity min of -51. are physically impossible indoor.
CO2_ElectroChemicalSensor and CO2_InfraredSensor both have different reading. This shows that there is either some calibration done or units are different. From my research, the infrared sensor is more accurate (more info in readme).

### Missing values
"""

print(df.isnull().sum())

"""Four columns have missing data:
- Humidity: 1,928 missing (19.3%)
- MetalOxideSensor_Unit2: 1,410 missing (14.1%)
- Ambient Light Level: 1,054 missing (10.5%)
- CO_GasSensor: 834 missing (8.3%)

All other columns are complete.

### Duplicate rows
"""

print("Duplicate rows:", df.duplicated().sum())

"""171 duplicate rows found. We will drop them during cleaning.

## 3. Categorical Column Inspection

Check the unique values in each categorical column before touching anything.

### Time of Day
"""

print(df["Time of Day"].unique())

"""4 clean values — no issues.

### HVAC Operation Mode
"""

print(df["HVAC Operation Mode"].unique())

"""23 unique values but only 6 logical states. The same value appears in uppercase, title case, and lowercase (COOLING_ACTIVE, Cooling_Active, cooling_active) Needs standardising.

### Ambient Light Level
"""

print(df["Ambient Light Level"].unique())

"""5 clean values — no issues.

### Activity Level
"""

print(df["Activity Level"].unique())

"""6 values representing only 3 states. Low Activity, Low_Activity, and LowActivity are all the same thing. Same problem for Moderate. Needs standardising.

## 4. Session ID Distribution
"""

print("Unique sessions:", df["Session ID"].nunique())
print()
print(df["Session ID"].value_counts().describe().round(1))

"""38 unique sessions. Each session contributes between 56 and 388 rows, with a mean of 263. Sessions are unequal in size — the largest session (388 rows) contributes about 7x as many rows as the smallest (56 rows).

"""

plt.figure(figsize=(14, 4))
df["Session ID"].value_counts().sort_index().plot(kind="bar", color="steelblue", edgecolor="none")
plt.title("Records per Session ID")
plt.xlabel("Session ID")
plt.ylabel("Row count")
plt.xticks(rotation=90, fontsize=7)
plt.tight_layout()
plt.show()

"""Sessions are spread across a wide range of IDs (not sequential). Row counts vary quite a bit. Sessions with very few rows (e.g. <100) may have incomplete sensor readings and could bias model training — worth keeping in mind for the ML pipeline.

## 5. Physical Anomaly Check

Before cleaning, check how many rows have values that are physically impossible indoors.
A valid indoor environment should have: Temperature 5–50 °C, Humidity 0–100 %, CO2 more than 0, CO more than 0.
"""

print("Temperature > 50 °C: ", (df["Temperature"] > 50).sum())
print("Temperature < 5 °C:  ", (df["Temperature"] < 5).sum())
print("Humidity < 0 %:      ", (df["Humidity"] < 0).sum())
print("Humidity > 100 %:    ", (df["Humidity"] > 100).sum())
print("CO2_InfraredSensor < 0:", (df["CO2_InfraredSensor"] < 0).sum())
print("CO_GasSensor < 0:      ", (df["CO_GasSensor"] < 0).sum())

"""- 795 rows have Temperature > 50 °C — sensor drift or data entry errors, not real indoor readings.
- 207 rows have Humidity < 0 % and another 207 have Humidity > 100 % — physically impossible.
- 113 rows have negative CO2 readings — sensor calibration failure.
- CO_GasSensor has no negative values.

These rows will have the bad values set to NaN and then imputed.

## 7. Numeric Distributions
"""

numeric_cols = ["Temperature", "Humidity", "CO2_InfraredSensor",
                "MetalOxideSensor_Unit1", "MetalOxideSensor_Unit2",
                "MetalOxideSensor_Unit3", "MetalOxideSensor_Unit4",
                "CO_GasSensor"]

fig, axes = plt.subplots(2, 4, figsize=(16, 7))
for ax, col in zip(axes.flat, numeric_cols):
    df[col].dropna().hist(bins=50, ax=ax, color="steelblue", edgecolor="none")
    ax.set_title(col, fontsize=9)
    ax.tick_params(labelsize=7)
plt.suptitle("Numeric Distributions (raw data, anomalies still present)", y=1.01)
plt.tight_layout()
plt.show()

"""Temperature and Humidity have a big range and the distribution is really skewed.(The invalid values identified)
The CO sensor seems to be categorical from what I see. The data type is float but there is only 5 distinct values. This signals to me that CO sensor is categorical.(Data type has to be changed in cleaning)

## 8. Activity Level Class Balance
"""

print(df["Activity Level"].value_counts())
print()
print(df["Activity Level"].value_counts(normalize=True).round(3))

_act_map = {
    "Low Activity":      "Low Activity",
    "Low_Activity":      "Low Activity",
    "LowActivity":       "Low Activity",
    "Moderate Activity": "Moderate Activity",
    "ModerateActivity":  "Moderate Activity",
    "High Activity":     "High Activity",
    "HighActivity":      "High Activity",
}
_order = ["Low Activity", "Moderate Activity", "High Activity"]
counts = df["Activity Level"].map(_act_map).value_counts().reindex(_order)
colors = ["#5B9BD5", "#ED7D31", "#A9D18E"]

plt.figure(figsize=(7, 4))
plt.bar(counts.index, counts, color=colors)

plt.title("Activity Level Class Distribution")
plt.ylabel("Row count")

for i, v in enumerate(counts):
    plt.text(i, v + 30, f"{v:,}\n({(v / len(df)) * 100:.1f}%)", ha="center", fontsize=9)

plt.tight_layout()
plt.show()

"""There is class inbalance
* low_activity : 57.7% of the dataset
* moderate_activity : 31.4% of the dataset
* high_activity : 10.9% of the dataset

There is 5x more low activity than high activity, this will lead to the ML model seeing disproportionate amount of low activity than high activity, this will lead the model to ignore the minority class. We will use class_weight='balanced' orr SMOTE oversampling in the ML training process. XGBOOST and random forest is also good to process unbalanced datasets. For AI evaluvation, macro F1 score will be used.

## 9. Activity Level by Time of Day
"""

# Normalise labels locally just for plotting — df is not modified
_act_map = {
    "Low Activity":      "low_activity",
    "Low_Activity":      "low_activity",
    "LowActivity":       "low_activity",
    "Moderate Activity": "moderate_activity",
    "ModerateActivity":  "moderate_activity",
    "High Activity":     "high_activity",
    "HighActivity":      "high_activity",
}
_act_series = df["Activity Level"].map(_act_map)
_tod_map = {v: v.lower() for v in df["Time of Day"].unique()}
_tod_series = df["Time of Day"].map(_tod_map)

act_order = ["low_activity", "moderate_activity", "high_activity"]
time_order = ["morning", "afternoon", "evening", "night"]
ct = pd.crosstab(_tod_series, _act_series).reindex(time_order)[act_order]

print("Counts:\n", ct, "\n\nRow proportions:\n", ct.div(ct.sum(axis=1), axis=0).round(2))

ct_pct = ct.div(ct.sum(axis=1), axis=0)

ct_pct.plot(kind="bar", stacked=True, width=0.6, color=["#5B9BD5", "#ED7D31", "#A9D18E"], rot=0, figsize=(8, 4))
plt.title("Activity Level Proportion by Time of Day")
plt.xlabel("")
plt.ylabel("Proportion")
plt.legend(title="Activity", bbox_to_anchor=(1, 1))

plt.tight_layout()
plt.show()

"""Morning and afternoon have the most high activity and moderate activity rows. Evening and night skew heavily toward low activity. People are less active late at night. Time of Day therefore carries useful information for predicting activity level beyond just temperature and gas readings. Just something to take note.

Evening has the most skewed profile. Morning is the most balanced across all three classes. The stacked bar makes the shift pattern easy to see and confirms Time of Day should be included as a feature in the ML model.

## 9. Correlation Heatmap
"""

NUMERIC_COLS = ["Temperature", "Humidity", "CO2_InfraredSensor",
                "MetalOxideSensor_Unit1", "MetalOxideSensor_Unit2",
                "MetalOxideSensor_Unit3", "MetalOxideSensor_Unit4",
                "CO_GasSensor"]

corr = df[NUMERIC_COLS].corr()

mask = np.triu(np.ones_like(corr, dtype=bool))

fig, ax = plt.subplots(figsize=(11, 9))
cmap = sns.diverging_palette(230, 20, as_cmap=True)

sns.heatmap(
    corr,
    mask=mask,
    cmap=cmap,
    center=0,
    vmin=-1, vmax=1,
    annot=True, fmt=".2f",
    linewidths=0.5,
    square=True,
    cbar_kws={"shrink": 0.7},
    ax=ax,
)
ax.set_title("Pairwise Pearson Correlations — All Numeric Features",
             fontsize=13, fontweight="bold", pad=14)
plt.tight_layout()
plt.show()

"""MetalOxideSensor_Unit2 and Unit4 are very highly correlated (r = 0.95) They might be measuring the same thing. We will consider dropping Unit2 in the ML notebook.

## 9. Data Cleaning

### Step 1 — Drop duplicates
"""

df_clean = df.drop_duplicates()
print("Rows after dropping duplicates:", len(df_clean))

"""171 duplicate rows removed. 9,829 rows remain.

### Step 2 — Fix physically impossible values

Set out-of-range values to NaN instead of dropping the rows — the rest of the row's data is still valid.
"""

df_clean.loc[df_clean["Temperature"] > 50, "Temperature"] = np.nan
df_clean.loc[df_clean["Humidity"] < 0,  "Humidity"] = np.nan
df_clean.loc[df_clean["Humidity"] > 100, "Humidity"] = np.nan
df_clean.loc[df_clean["CO2_InfraredSensor"] < 0, "CO2_InfraredSensor"] = np.nan

print(df_clean[["Temperature", "Humidity", "CO2_InfraredSensor"]].isnull().sum())

"""Temperature now has 795 more NaNs, Humidity gains 414, CO2_InfraredSensor gains 113. All will be imputed next.

### Step 3 — Impute missing values

Use session-level median for numeric columns. Rows within the same session share the same room state (same HVAC mode, same activity level), so the session median is more faithful than the global median.
Fall back to the global median for any session that is entirely NaN for a column.
"""

numeric_to_impute = ["Temperature", "Humidity", "CO2_InfraredSensor",
                     "MetalOxideSensor_Unit2", "CO_GasSensor"]

for col in numeric_to_impute:
    session_median = df_clean.groupby("Session ID")[col].transform("median")
    df_clean[col] = df_clean[col].fillna(session_median).fillna(df_clean[col].median())

# Ambient Light Level is categorical — use global mode
df_clean["Ambient Light Level"] = df_clean["Ambient Light Level"].fillna(
    df_clean["Ambient Light Level"].mode()[0]
)

print(df_clean.isnull().sum())

"""All missing values resolved. Every column now has 0 NaNs.

### Step 4 — Standardise categorical columns

Lowercase and strip whitespace, then replace spaces/dashes with underscores. Do HVAC and Activity Level which have the inconsistency problems we found in Section 3.
"""

for col in ["HVAC Operation Mode", "Activity Level"]:
    df_clean[col] = (df_clean[col]
                     .str.strip()
                     .str.lower()
                     .str.replace(r"[\s\-]+", "_", regex=True))

# Activity Level also has fused variants like "lowactivity" — map them too
act_map = {
    "lowactivity":      "low_activity",
    "moderateactivity": "moderate_activity",
    "highactivity":     "high_activity",
}
df_clean["Activity Level"] = df_clean["Activity Level"].replace(act_map)

"""Check the result:"""

print("HVAC Operation Mode:", sorted(df_clean["HVAC Operation Mode"].unique()))
print()
print("Activity Level:", sorted(df_clean["Activity Level"].unique()))

"""HVAC Operation Mode: 23 raw variants → 6 clean categories.
Activity Level: 6 raw variants → 3 clean categories.
No information lost — only inconsistent formatting fixed.

### Step 5 — Drop CO2_ElectroChemicalSensor

We have established that there are 2 CO2 sensors and they have different values. Since they are essentially measuring the same thing, we are going to remove the electrochemical sensor as from my research, the electrochemical sensor is less accurate (More info in README)
"""

df_clean = df_clean.drop(columns=["CO2_ElectroChemicalSensor"])
print("Columns remaining:", df_clean.columns.tolist())

"""## Before And After Cleaning"""

# Before cleaning — raw df
print("=== BEFORE CLEANING ===")
print(f"Shape: {df.shape}")
print(f"\nDuplicates: {df.duplicated().sum()}")
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nPhysically impossible values:")
print(f"  Temperature > 50°C:     {(df['Temperature'] > 50).sum()}")
print(f"  Humidity < 0%:          {(df['Humidity'] < 0).sum()}")
print(f"  Humidity > 100%:        {(df['Humidity'] > 100).sum()}")
print(f"  CO2_InfraredSensor < 0: {(df['CO2_InfraredSensor'] < 0).sum()}")
print(f"\nActivity Level variants ({df['Activity Level'].nunique()}):\n{df['Activity Level'].value_counts()}")
print(f"\nHVAC Operation Mode variants ({df['HVAC Operation Mode'].nunique()}):\n{df['HVAC Operation Mode'].value_counts()}")
print(f"\nColumns ({len(df.columns)}):\n{df.columns.tolist()}")

# After cleaning — df_clean
print("=== AFTER CLEANING ===")
print(f"Shape: {df_clean.shape}")
print(f"\nDuplicates: {df_clean.duplicated().sum()}")
print(f"\nMissing values:\n{df_clean.isnull().sum()}")
print(f"\nPhysically impossible values:")
print(f"  Temperature > 50°C:     {(df_clean['Temperature'] > 50).sum()}")
print(f"  Humidity < 0%:          {(df_clean['Humidity'] < 0).sum()}")
print(f"  Humidity > 100%:        {(df_clean['Humidity'] > 100).sum()}")
print(f"  CO2_InfraredSensor < 0: {(df_clean['CO2_InfraredSensor'] < 0).sum()}")
print(f"\nActivity Level variants ({df_clean['Activity Level'].nunique()}):\n{df_clean['Activity Level'].value_counts()}")
print(f"\nHVAC Operation Mode variants ({df_clean['HVAC Operation Mode'].nunique()}):\n{df_clean['HVAC Operation Mode'].value_counts()}")
print(f"\nColumns ({len(df_clean.columns)}):\n{df_clean.columns.tolist()}")
print(f"\nDropped columns: {[c for c in df.columns if c not in df_clean.columns]}")

"""
cols = ["Temperature", "Humidity", "CO2_InfraredSensor", "MetalOxideSensor_Unit2", "CO_GasSensor", "Ambient Light Level"]

print("=== NUMERIC SUMMARY BEFORE ===")
print(df[cols].describe().round(2))
print("\n=== NUMERIC SUMMARY AFTER ===")
print(df_clean[cols].describe().round(2))"""

# Delta summary — everything that changed in one place
rows_dropped   = len(df) - len(df_clean)
dupes_dropped  = df.duplicated().sum()
cols_dropped   = [c for c in df.columns if c not in df_clean.columns]
missing_before = df.isnull().sum().sum()
missing_after  = df_clean.isnull().sum().sum()
hvac_before    = df["HVAC Operation Mode"].nunique()
hvac_after     = df_clean["HVAC Operation Mode"].nunique()
act_before     = df["Activity Level"].nunique()
act_after      = df_clean["Activity Level"].nunique()

print("=== CLEANING DELTA ===")
print(f"Rows:              {len(df):,}  →  {len(df_clean):,}  ({rows_dropped} dropped — {dupes_dropped} duplicates)")
print(f"Columns:           {len(df.columns)}  →  {len(df_clean.columns)}  (dropped: {cols_dropped})")
print(f"Total missing:     {missing_before:,}  →  {missing_after:,}")
print(f"Impossible Temp:   {(df['Temperature'] > 50).sum()}  →  {(df_clean['Temperature'] > 50).sum()}  (set to NaN, imputed)")
print(f"Impossible Humid:  {(df['Humidity'] < 0).sum() + (df['Humidity'] > 100).sum()}  →  {(df_clean['Humidity'] < 0).sum() + (df_clean['Humidity'] > 100).sum()}  (set to NaN, imputed)")
print(f"Negative CO2:      {(df['CO2_InfraredSensor'] < 0).sum()}  →  {(df_clean['CO2_InfraredSensor'] < 0).sum()}  (set to NaN, imputed)")
print(f"HVAC variants:     {hvac_before}  →  {hvac_after}")
print(f"Activity variants: {act_before}  →  {act_after}")

"""## 15. Summary and Export

**What was done:**
- Dropped 171 duplicate rows
- Set 795 impossible Temperature values, 414 impossible Humidity values, and 113 negative CO2 values to NaN, then imputed with session-level medians
- Resolved Ambient Light Level NaNs with mode imputation
- Standardised HVAC Operation Mode (23 variants → 6) and Activity Level (6 variants → 3)
- Dropped CO2_ElectroChemicalSensor (calibration offset only, no independent signal)

**For the ML notebook:**
- Target variable: `Activity Level` (3-class classification)
- Apply log1p to Temperature and Humidity before feeding to linear models
- Consider dropping MetalOxideSensor_Unit2 (r = 0.95 with Unit4)
- Use Session ID for GroupShuffleSplit to avoid data leakage across sessions
"""

df_clean.to_csv("gas_monitoring_cleaned.csv", index=False)
print(f"Saved. Shape: {df_clean.shape}")